export const SET_CART = 'SET_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const CHANGE_CART_ITEM_QUANTITY = 'CHANGE_CART_ITEM_QUANTITY';
export const GET_CART_ITEM_ID = 'GET_CART_ITEM_ID';
